roberticopapa/urls.py
from django.conf.urls import url
from django.contrib import admin
import publicador.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', publicador.views.home_page, name='home'),
    url(r'^publicador/$', publicador.views.home_page, name='home'),

    url(r'^publicador/crea_publicacion$', publicador.views.crea_publicacion, name='crea_publicacion'),
    url(r'^publicador/(\d+)/recibe_fotos$', publicador.views.recibe_fotos, name='recibe_fotos'),
    url(r'^publicador/(\d+)/guarda_publicacion$', publicador.views.guarda_publicacion, name='guarda_publicacion'),
    url(r'^publicador/(\d+)/ver_publicacion$', publicador.views.ver_publicacion, name='ver_publicacion'),
    url(r'^publicador/imagenes/(.+)$', publicador.views.ver_imagen, name='ver_imagen'),
    url(r'^publicador/(\d+)/publicar$', publicador.views.publicar, name='publicar'),
    url(r'^publicador/(\d+)/eop$', publicador.views.eop, name='eop'),
    url(r'^publicador/(\d+)/editar$', publicador.views.editar, name='editar'),
    url(r'^publicador/(\d+)/eliminar$', publicador.views.eliminar, name='eliminar'),
    url(r'^publicador/cambia_contrasena$', publicador.views.cambia_contrasena, name='cambia_contrasena'),

]

publicador/models.py
from django.db import models
import datetime

class Publicacion(models.Model):
    grupo = models.TextField(default='')
    nombre = models.TextField(default='')
    precio = models.TextField(default='')
    descripcion = models.TextField(default='')
    numero_fotos = models.IntegerField(default=0)
    numero_publicaciones = models.IntegerField(default=1)
    def __str__(self):
        return self.nombre

class PublicacionImagen(models.Model):
    publicacion = models.ForeignKey(Publicacion, default=None)
    md5 = models.TextField(default='')
    imagen = models.ImageField(upload_to='publicador/imagenes', default=None)

class PublicacionFecha(models.Model):
    publicacion = models.ForeignKey(Publicacion, default=None)
    celery_id = models.TextField(default='')
    fecha = models.DateTimeField(default=datetime.datetime.now)
    cancelado = models.BooleanField(default=False)

class Cuenta(models.Model):
    email = models.TextField(default='')
    password = models.TextField(default='')

publicador/views.py
from django.shortcuts import render, redirect
from django.core.files.base import ContentFile
from publicador.models import Publicacion, PublicacionImagen, PublicacionFecha, Cuenta
from django.http import HttpResponse
import mimetypes
from publicador.tasks import enviar
import datetime
import hashlib
from pytz import timezone
from celery.task.control import revoke

# Create your views here.
def home_page(request):
    if len(Cuenta.objects.all()) == 0:
        return render(request, 'cambia_contrasena.html')
    else:
        publicaciones = Publicacion.objects.all()
        enviados = []
        for publicacion in publicaciones:
            if len(PublicacionFecha.objects.filter(publicacion_id=publicacion.id)) > 0 and PublicacionFecha.objects.filter(publicacion_id=publicacion.id)[0].celery_id != '':
                enviados.append(True)
            else:
                enviados.append(False)
        return render(request, 'home.html', {
            'pe': zip(publicaciones, enviados)
        })

def crea_publicacion(request):
    publicacion = Publicacion.objects.create(
        grupo = request.POST.get('grupo_texto', ''),
        nombre = request.POST.get('nombre_texto', ''),
        precio = request.POST.get('precio_texto', ''),
        descripcion = request.POST.get('descripcion_texto', ''),
        numero_fotos = (0 if request.POST.get('num_fotos') == '' else int(request.POST.get('num_fotos', 0))),
        numero_publicaciones = (0 if request.POST.get('num_publicaciones') == '' else int(request.POST.get('num_publicaciones', 0))),
    )

    return redirect('/publicador/%d/recibe_fotos' % (publicacion.id,))

def cambia_contrasena(request):
    email = request.POST.get('email_texto', default='')
    password = request.POST.get('password_texto', default='')
    if email == '':
        return render(request, 'cambia_contrasena.html', {
            'cuenta': Cuenta.objects.all()[0] if len(Cuenta.objects.all()) != 0 else None,
            'cambio': False,
        })
    else:
        if len(Cuenta.objects.all()) == 0:
            Cuenta.objects.create(email = email, password = password)
        else:
            cuenta = Cuenta.objects.all()[0]
            cuenta.email = email
            cuenta.password = password
            cuenta.save()
        return render(request, 'cambia_contrasena.html', {
            'cuenta': Cuenta.objects.all()[0] if len(Cuenta.objects.all()) != 0 else None,
            'cambio': True,
        })

def recibe_fotos(request, publicacion_id):
    publicacion = Publicacion.objects.get(id = publicacion_id)
    return render(request, 'recibe_fotos.html', {
        'range_imagenes': range(publicacion.numero_fotos),
        'range_fechas': range(publicacion.numero_publicaciones),
        'publicacion': publicacion,
    })

def eliminar(request, publicacion_id):
    for tarea in PublicacionFecha.objects.filter(publicacion_id=publicacion_id):
        revoke(tarea.celery_id)
        tarea.delete()
    for imagen in PublicacionImagen.objects.filter(publicacion_id=publicacion_id):
        imagen.delete()
    Publicacion.objects.get(id = publicacion_id).delete()
    return redirect('/publicador/')
    

def guarda_publicacion(request, publicacion_id):
    publicacion = Publicacion.objects.get(id = publicacion_id)

    publicacion.grupo = request.POST.get('grupo_texto', '')
    publicacion.nombre = request.POST.get('nombre_texto', '')
    publicacion.precio = request.POST.get('precio_texto', '')
    publicacion.descripcion = request.POST.get('descripcion_texto', '')
    publicacion.save()

    for archivo in request.FILES.getlist('imagen'):
        barchivo = archivo.read()
        if len(PublicacionImagen.objects.filter(publicacion=publicacion, md5 = hashlib.md5(barchivo).hexdigest())) == 0:
            pi = PublicacionImagen.objects.create(publicacion=publicacion)
            pi.md5 = hashlib.md5(barchivo).hexdigest()
            pi.imagen.save('%s_%s' % (publicacion_id, archivo.name), archivo)
            pi.save()
    for fecha in request.POST.getlist('fecha'):
        if len(PublicacionFecha.objects.filter(fecha = timezone('America/Caracas').localize(datetime.datetime.strptime(fecha, '%Y-%m-%dT%H:%M')))) == 0:
            pi = PublicacionFecha.objects.create(publicacion=publicacion, fecha = timezone('America/Caracas').localize(datetime.datetime.strptime(fecha, '%Y-%m-%dT%H:%M')))
    return redirect('/publicador/%d/ver_publicacion' % (publicacion.id,))

def ver_imagen(request, nombre):
    f = open("publicador/imagenes/%s" % nombre, mode="rb")
    imagen = f.read()
    response = HttpResponse(imagen, content_type=mimetypes.guess_type(nombre))
    return response

def eop(request, publicacion_id):
    editar = request.POST.get('editar', False)
    publicar = request.POST.get('publicar', False)
    eliminar = request.POST.get('eliminar', False)
    if editar and not publicar and not eliminar:
        return redirect('/publicador/%s/editar' % (publicacion_id,))
    elif publicar and not eliminar and not editar:
        return redirect('/publicador/%s/publicar' % (publicacion_id,))
    elif eliminar and not publicar and not editar:
        return redirect('/publicador/%s/eliminar' % (publicacion_id,))
    return None

def editar(request, publicacion_id):
    publicacion = Publicacion.objects.get(id = publicacion_id)
    return render(request, 'editar.html', {
        'publicacion': publicacion,
    })
    pass

def ver_publicacion(request, publicacion_id):
    publicacion = Publicacion.objects.get(id = publicacion_id)
    imagenes = [x.imagen for x in PublicacionImagen.objects.filter(publicacion_id=publicacion_id)]
    fechas = [publicacionfecha.fecha.astimezone(timezone("America/Caracas")).strftime('%Y-%m-%d %I:%M %p') for publicacionfecha in PublicacionFecha.objects.filter(publicacion_id=publicacion_id)]
    if len(PublicacionFecha.objects.filter(publicacion_id=publicacion_id)) > 0: # este condicional es una basura y ofensivo
        return render(request, 'ver_publicacion.html', {
            'publicacion': publicacion,
            'imagenes': imagenes,
            'fechas': fechas,
            'enviado': True if PublicacionFecha.objects.filter(publicacion_id=publicacion_id)[0].celery_id != '' else False
        })
    else:
        return render(request, 'ver_publicacion.html', {
            'publicacion': publicacion,
            'imagenes': imagenes,
            'fechas': fechas,
            'enviado': False
        })

def publicar(request, publicacion_id):
    publicacion = Publicacion.objects.get(id = publicacion_id)
    imagenes = [pi.imagen for pi in PublicacionImagen.objects.filter(publicacion_id=publicacion_id)]
    rutas_imagenes = [imagen.path for imagen in imagenes]
    for pf in PublicacionFecha.objects.filter(publicacion_id=publicacion_id):
        if pf.celery_id == '':
            pf.celery_id = enviar.apply_async([publicacion.id], eta=pf.fecha,).id
            pf.save()
            h = 'Se envió la publicación'
        else:
            h = 'La publicación ya había sido enviada'
    return render(request, 'publicar.html', {
        'publicacion': publicacion,
        'imagenes': imagenes,
        'header': h
    })

publicador/templates/cambia_contrasena.html
<!DOCTYPE html>
<html>
    <head>
        <title>Editar publicación</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        {% if cambio %}
        <meta http-equiv="refresh" content="2; url=/" />
        {% endif %}
    </head>
    <body>
        {% if not cambio %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Cambiar contraseña</div>
                    <div class="panel-body">
                        <form method="POST" action="/publicador/cambia_contrasena" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="id_email">E-mail</label>
                                <input class="form-control" id="id_email" name="email_texto" value="{{ cuenta.email }}" required />
                            </div>
                            <div class="form-group">
                                <label for="id_nombre">Password</label>
                                <input class="form-control" id="id_password" name="password_texto" required />
                            </div>
                            <input class="btn btn-default" type="submit" id="enviar" />
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <h1 class="text-center">La contraseña ha sido cambiada.</h1>
        {% endif %}
    </body>
</html>

publicador/templates/editar.html
<!DOCTYPE html>
<html>
    <head>
        <title>Editar publicación</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Editar publicación</div>
                    <div class="panel-body">
                        <form method="POST" action="/publicador/{{ publicacion.id }}/guarda_publicacion" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="id_grupo">Grupo de Facebook</label>
                                <input class="form-control" id="id_grupo" name="grupo_texto" value="{{ publicacion.grupo }}" placeholder="Grupo de Facebook" required />
                            </div>
                            <div class="form-group">
                                <label for="id_nombre">Nombre del producto</label>
                                <input class="form-control" id="id_nombre" name="nombre_texto" value="{{ publicacion.nombre }}" placeholder="Nombre" required />
                            </div>
                            <div class="form-group">
                                <label for="id_precio">Precio del producto</label>
                                <input class="form-control" id="id_precio" name="precio_texto" value="{{ publicacion.precio }}" placeholder="Precio" type="number" required />
                            </div>
                            <div class="form-group">
                                <label for="id_descripcion">Descripcion del producto</label>
                                <input class="form-control" id="id_description" name="descripcion_texto" value="{{ publicacion.descripcion }}" placeholder="Descripcion" />
                            </div>
                            <input class="btn btn-default" type="submit" id="enviar" />
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

publicador/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Publicador de ventas de facebook</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <p class="navbar-text navbar-right"><a href="/publicador/cambia_contrasena" class="navbar-link">Cambiar contraseña</a></p>
                </div>
            </div>
        </nav>
        <div class="wrapper container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">Realizar publicación</div>
                        <div class="panel-body">
                            <form method="POST" action="/publicador/crea_publicacion">
                                <div class="form-group">
                                    <label for="id_grupo">Grupo de Facebook</label>
                                    <input type="text" class="form-control" id="id_grupo" name="grupo_texto" required />
                                </div>
                                <div class="form-group">
                                    <label for="id_nombre">Nombre del producto</label>
                                    <input type="text" class="form-control" id="id_nombre" name="nombre_texto" required />
                                </div>
                                <div class="form-group">
                                    <label for="id_precio">Precio del producto</label>
                                    <input type="number" class="form-control" id="id_precio" name="precio_texto" min="1" required />
                                </div>
                                <div class="form-group">
                                    <label for="id_descripcion">Descripcion del producto</label>
                                    <textarea class="form-control" id="id_description" name="descripcion_texto"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="id_num_fotos">Número de fotos</label>
                                    <input class="form-control" id="id_num_fotos" name="num_fotos" type="number" min="0" value="0" />
                                </div>
                                <div class="form-group">
                                    <label for="id_num_publicaciones">Número de veces a publicar</label>
                                    <input class="form-control" id="id_num_publicaciones" name="num_publicaciones" type="number" min="1" value="1" />
                                </div>
                                    <input class="btn btn-default" type="submit" id="enviar" />
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">Publicaciones</div>
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <th>
                                        #
                                    </th>
                                    <th>
                                        Publicación
                                    </th>
                                    <th>
                                        Estado
                                    </th>
                                </tr>
                                {% for publicacion, enviado in pe %}
                                {% if enviado %}<tr class="success">{% else %}<tr>{% endif %}
                                    <td><a href="/publicador/{{ publicacion.id }}/ver_publicacion">{{ publicacion.id }}</a></td>
                                    <td>{{ publicacion.nombre }}</td>
                                    <td>{% if enviado %}Enviado{% else %}No enviado{% endif %}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

publicador/templates/publicar.html
<!DOCTYPE html>
<html>
    <head>
        <title>Publicar</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <h1 class="text-center">{{ header }}</h1>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Publicación</div>
                    <div class="panel-body">
                        <dl class="dl-horizontal">
                            <dt>Grupo</dt>
                            <dd>{{ publicacion.grupo }}</dd>
                            <dt>Nombre del artículo</dt>
                            <dd>{{ publicacion.nombre }}</dd>
                            <dt>Precio del artículo</dt>
                            <dd>{{ publicacion.precio }}</dd>
                            <dt>Descripción</dt>
                            <dd>{{ publicacion.descripcion }}</dd>
                            <dt>Estado</dt>
                            {% if enviado %}
                            <dd>Enviado</dd>
                            {% else %}
                            <dd>No enviado</dd>
                            {% endif %}
                            <dt>Horas de publicación</dt>
                            {% for fecha in fechas %}
                            <dd>{{ fecha }}</dd>
                            {% endfor %}
                        </dl>
                    </div>
                    <div class="panel-body">
                        <div class="container">
                        {% for imagen in imagenes %}
                            <div class="col-md-4">
                                <img src="/{{ imagen }}" class="img-thumbnail" width="300px" /> <br />
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

publicador/templates/recibe_fotos.html
<!DOCTYPE html>
<html>
    <head>
        <title>Indicar fotos y fechas</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Realizar publicación</div>
                    <div class="panel-body">
                        <form method="POST" action="/publicador/{{ publicacion.id }}/guarda_publicacion" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="id_grupo">Grupo de Facebook</label>
                                <input class="form-control" id="id_grupo" name="grupo_texto" value="{{ publicacion.grupo }}" placeholder="Grupo de Facebook" required />
                            </div>
                            <div class="form-group">
                                <label for="id_nombre">Nombre del producto</label>
                                <input class="form-control" id="id_nombre" name="nombre_texto" value="{{ publicacion.nombre }}" placeholder="Nombre" required />
                            </div>
                            <div class="form-group">
                                <label for="id_precio">Precio del producto</label>
                                <input class="form-control" id="id_precio" name="precio_texto" value="{{ publicacion.precio }}" placeholder="Precio" type="number" required />
                            </div>
                            <div class="form-group">
                                <label for="id_descripcion">Descripcion del producto</label>
                                <input class="form-control" id="id_description" name="descripcion_texto" value="{{ publicacion.descripcion }}" placeholder="Descripcion" />
                            </div>
                                {% for k in range_imagenes %}
                            <div class="form-group">
                                <label for="id_image{{ k }}">Imagen {{ k|add:"1" }}</label>
                                <input id="id_imagen{{ k }}" name="imagen" type="file" accept="image/*" required />
                            </div>
                                {% endfor %}
                                {% for k in range_fechas %}
                            <div class="form-group">
                                <label for="id_image{{ k }}">Fecha y hora de publicación {{ k|add:"1" }}</label>
                                <input class="form-control" id="id_fecha{{ k }}" name="fecha" type="datetime-local" required />
                                <p class="help-block">De no estar usando Chrome, usar formato AAAA-MM-DDTHH:MM, eg. 1999-12-30T19:34</p>
                            </div>
                                {% endfor %}
                                <input class="form-control" type="submit" id="enviar" />
                                {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

publicador/templates/ver_publicacion.html
<!DOCTYPE html>
<html>
    <head>
        <title>Ver publicación</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Publicación</div>
                    <div class="panel-body">
                        <dl class="dl-horizontal">
                            <dt>Grupo</dt>
                            <dd>{{ publicacion.grupo }}</dd>
                            <dt>Nombre del artículo</dt>
                            <dd>{{ publicacion.nombre }}</dd>
                            <dt>Precio del artículo</dt>
                            <dd>{{ publicacion.precio }}</dd>
                            <dt>Descripción</dt>
                            <dd>{{ publicacion.descripcion }}</dd>
                            <dt>Estado</dt>
                            {% if enviado %}
                            <dd>Enviado</dd>
                            {% else %}
                            <dd>No enviado</dd>
                            {% endif %}
                            <dt>Horas de publicación</dt>
                            {% for fecha in fechas %}
                            <dd>{{ fecha }}</dd>
                            {% endfor %}
                        </dl>
                    </div>
                    <div class="panel-body">
                        <div class="container">
                        {% for imagen in imagenes %}
                            <div class="col-md-4">
                                <img src="/{{ imagen }}" class="img-thumbnail" width="300px" /> <br />
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                    <div class="panel-body">
                        <form method="POST" action="/publicador/{{ publicacion.id }}/eop">
                            <input class="btn btn-default" name="publicar" value="Publicar" type="submit">
                            <input class="btn btn-default" name="editar" value="Editar" type="submit">
                            <input class="btn btn-default" name="eliminar" value="Eliminar" type="submit">
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>